### ISSUE TITLE
Left-off todos related to compiler warnings

### ISSUE THREAD

**Issue by lan496** [spglib/spglib#289]
Left-off todos related to compiler warnings suggested by @LecrisUT 
Related: https://github.com/spglib/spglib/pull/278

## TODO
- [x] warning regarding passing non-const array to const array. That should be perfectly fine, but why does the compiler trigger a warning about it #302 
- [ ] uninitialized warnings should be fixed #297 
- [ ] make warnings become error: [CMAKE_COMPILE_WARNING_AS_ERROR](https://cmake.org/cmake/help/latest/variable/CMAKE_COMPILE_WARNING_AS_ERROR.html#variable:CMAKE_COMPILE_WARNING_AS_ERROR)
