### ISSUE TITLE
Releasing v2.3.0

### ISSUE THREAD

**Issue by lan496** [spglib/spglib#384]
Let's release the next minor version after the New Year holidays. I think the dropping of Python 3.7 should be treated in a minor version change.

## TODOs
- [x] https://github.com/spglib/spglib/issues/381
- [x] https://github.com/spglib/spglib/issues/373
- [x] https://github.com/spglib/spglib/issues/380
- [x] https://github.com/spglib/spglib/pull/362
- ~~issue with scikit-build-core 0.8.0~~

**Comment by lan496** [comment]
CC: @atztogo @LecrisUT

**Comment by atztogo** [comment]
If no conflict, I think we can merge #379. However, I'd like to revisit the approach for implementing the layer group. My concern is that the current method may overlook various edge cases, making it challenging for the spglib project team, especially as membership changes, to maintain the code effectively.

**Comment by lan496** [comment]
I also think the layer group implementation needs more formulation and clarification for the algorithm. I will drop it from the next TODO list.

**Comment by LecrisUT** [comment]
I will address #271 soon. Finally had some time to update [CMakeExtraUtils](https://github.com/LecrisUT/CMakeExtraUtils). I just need to copy the `DynamicVersion` module from there.

**Comment by LecrisUT** [comment]
We should include #362 in the TODO

**Comment by lan496** [comment]
updated

**Comment by lan496** [comment]
Thank you both! I will prepare a release note on the weekend.

**Comment by LecrisUT** [comment]
There's an issue with the scikit-build-core 0.8.0 that just got released, let me investigate that quickly

**Comment by LecrisUT** [comment]
Ok, it's not scikit-build-core, it's just RTD does `git clone shallow`. Weird that it did not error when we merged `DynamicVersion`

**Comment by lan496** [comment]
@LecrisUT Do you include https://github.com/spglib/spglib/pull/402 in 2.3 milestone?

**Comment by LecrisUT** [comment]
> @LecrisUT Do you include #402 in 2.3 milestone?

Oops, I must have missclicked, that's for 2.4
