### ISSUE TITLE
Plan to annotate Python API with backward compatibility

### ISSUE THREAD

**Issue by lan496** [spglib/spglib#388]
## TODO
- [x] Sync document and docstring: https://github.com/spglib/spglib/pull/387
- [x] Introduce mypy (and ruff) for type checking https://github.com/spglib/spglib/pull/392
- [x] Annotate `cell` as `typing.NamedTuple`
- [x] Annotate returned dictionaries as `typing.TypedDict`
