### ISSUE TITLE
Release v2.4.0

### ISSUE THREAD

**Issue by lan496** [spglib/spglib#434]
Let's release type check (merged in https://github.com/spglib/spglib/pull/420) because the recent drop of ase.Atoms seems to cause surprise to not a few users.

## TODO
- [x] https://github.com/spglib/spglib/pull/308
- [x] https://github.com/spglib/spglib/pull/435
- [x] https://github.com/spglib/spglib/pull/437
- [x] https://github.com/spglib/spglib/pull/457
- [x]  https://github.com/spglib/spglib/pull/431

@LecrisUT @atztogo Do you have any leftovers for the next minor version?

**Comment by atztogo** [comment]
Thanks @lan496. Let's do it.

**Comment by LecrisUT** [comment]
On my side only #308, everything else can be bumped up

**Comment by LecrisUT** [comment]
Let's see how #435 goes, if all goes well, it would make sense to include it as well.

Edit: It actually works, so let's add it in as well
Edit2: Might be worth having #437 as well. That one solves a windows issue

**Comment by LecrisUT** [comment]
Small note, @lan496 when you make the release note, check that they are in order and not duplicated

**Comment by lan496** [comment]
Thank you both! I've updated the todo list in the first comment.

**Comment by LecrisUT** [comment]
I've added 2 PRs for this release since it seems it is a major nuisance to the users

**Comment by lan496** [comment]
@atztogo @LecrisUT Can I go on to releasing v2.4.0?

**Comment by LecrisUT** [comment]
On the feature side, all is good. Milestone wise there is #459 we can include, would be nice to have the full CI checks green again.

But don't forget to fix the `changelog.md` before tagging. There are duplicated `Python interface` and `C interface` sections that sneaked in some rebase

**Comment by lan496** [comment]
@LecrisUT Thanks. Then, let's release the next version after merging #459.

**Comment by LecrisUT** [comment]
Need to investigate #469 and #468, depending on the result, it might be easier to post a bugfix. But until then, let's hold off creating the release manually

**Comment by chenrui333** [comment]
also need a github release cc @lan496 

relates to https://github.com/Homebrew/homebrew-core/pull/168648

**Comment by LecrisUT** [comment]
The release is in draft, but we are holding off until any PR or commit is added https://github.com/spglib/spglib/issues/468#issuecomment-2050154383. The issue is about https://github.com/scikit-build/scikit-build-core/issues/695, where the tar archive changes after a single commit is added due to `%D` in `.git_archival.txt`. I am investigating now if there is any fix for it
