### ISSUE TITLE
Release v2.5.0

### ISSUE THREAD

**Issue by lan496** [spglib/spglib#486]
## TODO
- [x] https://github.com/spglib/spglib/pull/479
- [x] https://github.com/spglib/spglib/pull/485
- [x] https://github.com/spglib/spglib/pull/490
- [x] https://github.com/spglib/spglib/issues/407

@atztogo @LecrisUT Please update todos for the next minor release

**Comment by atztogo** [comment]
This is not directly related to this isssue, but for new release, adding typing-extensions to conda package build would be helpful for the dependency chain of conda forge packages. I currently pin spglib < 2.4 for phonopy and phono3py conda forge package builds. Otherwise, those packages can not be built.

https://github.com/conda-forge/spglib-feedstock/issues/112

**Comment by LecrisUT** [comment]
Let's see how [this comment](https://github.com/spglib/spglib/pull/485#discussion_r1590630817) goes. I think one point is to convert all plain `dict` to `TypedDict` + `dataclass` or `dataclass` + `Mapping` interface.

**Comment by lan496** [comment]
I would like to include https://github.com/spglib/spglib/pull/490 as well in the next release.

**Comment by LecrisUT** [comment]
Let me try to run the CI for numpy 2.0 for #407 and maybe simplify it a bit.

**Comment by LecrisUT** [comment]
@lan496 One final task that I noticed with #498 there are sections where we are calling the deprecated interface of `DictInterface`, e.g. 
https://github.com/spglib/spglib/blob/9acbe6dcd8ceedbec76426b6d107c46a6c9b7484/python/spglib/spglib.py#L1094-L1098
And I've been thinking about
https://github.com/spglib/spglib/blob/9acbe6dcd8ceedbec76426b6d107c46a6c9b7484/python/spglib/spglib.py#L92-L98
I think those are better outside of the TYPE_CHECKING. Reasoning is that I was thinking how to deal with the complex documentation like [`Cell`](https://github.com/spglib/spglib/blob/9acbe6dcd8ceedbec76426b6d107c46a6c9b7484/python/spglib/spglib.py#L519-L554) and I think that it can be incorporated in the TypeAlias itself, but that would require to move the definition outside conditional, especially for IDE support.

**Comment by lan496** [comment]
@LecrisUT Thanks. I'll fix both in https://github.com/spglib/spglib/pull/501

**Comment by lan496** [comment]
Successfully released 🎉
https://pypi.org/project/spglib/2.5.0/
https://github.com/spglib/spglib/releases/tag/v2.5.0
